/**
 * @license
 * Lo-Dash 2.4.1 (Custom Build) lodash.com/license | Underscore.js 1.5.2 underscorejs.org/LICENSE
 * Build: `lodash exports="amd" include="forEach,merge,clone" --minify --output src/lodash.js`
 */
;(function(){function n(n){return typeof n.toString!="function"&&typeof(n+"")=="string"}function t(n){n.length=0,w.length<x&&w.push(n)}function e(n,t,e){t||(t=0),typeof e=="undefined"&&(e=n?n.length:0);var r=-1;e=e-t||0;for(var o=Array(0>e?0:e);++r<e;)o[r]=n[t+r];return o}function r(){}function o(n){function t(){if(o){var n=e(o);Z.apply(n,arguments)}if(this instanceof t){var a=i(r.prototype),n=r.apply(a,n||arguments);return v(n)?n:a}return r.apply(u,n||arguments)}var r=n[0],o=n[2],u=n[4];return ft(t,n),t
}function u(r,o,i,a,c){if(i){var f=i(r);if(typeof f!="undefined")return f}if(!v(r))return r;var l=M.call(r);if(!$[l]||!ct.nodeClass&&n(r))return r;var s=it[l];switch(l){case D:case F:return new s(+r);case B:case R:return new s(r);case N:return f=s(r.source,S.exec(r)),f.lastIndex=r.lastIndex,f}if(l=lt(r),o){var p=!a;a||(a=w.pop()||[]),c||(c=w.pop()||[]);for(var g=a.length;g--;)if(a[g]==r)return c[g];f=l?s(r.length):{}}else f=l?e(r):bt({},r);return l&&(Y.call(r,"index")&&(f.index=r.index),Y.call(r,"input")&&(f.input=r.input)),o?(a.push(r),c.push(f),(l?yt:ht)(r,function(n,t){f[t]=u(n,o,i,a,c)
}),p&&(t(a),t(c)),f):f}function i(n){return v(n)?rt(n):{}}function a(n,t,e){if(typeof n!="function")return j;if(typeof t=="undefined"||!("prototype"in n))return n;var r=n.__bindData__;if(typeof r=="undefined"&&(ct.funcNames&&(r=!n.name),r=r||!ct.funcDecomp,!r)){var o=U.call(n);ct.funcNames||(r=!A.test(o)),r||(r=C.test(o),ft(n,r))}if(false===r||true!==r&&1&r[1])return n;switch(e){case 1:return function(e){return n.call(t,e)};case 2:return function(e,r){return n.call(t,e,r)};case 3:return function(e,r,o){return n.call(t,e,r,o)
};case 4:return function(e,r,o,u){return n.call(t,e,r,o,u)}}return m(n,t)}function c(n){function t(){var n=s?f:this;if(u){var h=e(u);Z.apply(h,arguments)}return(a||g)&&(h||(h=e(arguments)),a&&Z.apply(h,a),g&&h.length<l)?(o|=16,c([r,y?o:-4&o,h,null,f,l])):(h||(h=arguments),p&&(r=n[b]),this instanceof t?(n=i(r.prototype),h=r.apply(n,h),v(h)?h:n):r.apply(n,h))}var r=n[0],o=n[1],u=n[2],a=n[3],f=n[4],l=n[5],s=1&o,p=2&o,g=4&o,y=8&o,b=r;return ft(t,n),t}function f(n,t,e,r,o){(lt(t)?d:ht)(t,function(t,u){var i,a,c=t,l=n[u];
if(t&&((a=lt(t))||dt(t))){for(c=r.length;c--;)if(i=r[c]==t){l=o[c];break}if(!i){var s;e&&(c=e(l,t),s=typeof c!="undefined")&&(l=c),s||(l=a?lt(l)?l:[]:dt(l)?l:{}),r.push(t),o.push(l),s||f(l,t,e,r,o)}}else e&&(c=e(l,t),typeof c=="undefined"&&(c=t)),typeof c!="undefined"&&(l=c);n[u]=l})}function l(n,t,r,u,i,a){var f=1&t,s=4&t,p=16&t,g=32&t;if(!(2&t||b(n)))throw new TypeError;p&&!r.length&&(t&=-17,p=r=false),g&&!u.length&&(t&=-33,g=u=false);var y=n&&n.__bindData__;return y&&true!==y?(y=e(y),y[2]&&(y[2]=e(y[2])),y[3]&&(y[3]=e(y[3])),!f||1&y[1]||(y[4]=i),!f&&1&y[1]&&(t|=8),!s||4&y[1]||(y[5]=a),p&&Z.apply(y[2]||(y[2]=[]),r),g&&tt.apply(y[3]||(y[3]=[]),u),y[1]|=t,l.apply(null,y)):(1==t||17===t?o:c)([n,t,r,u,i,a])
}function s(){K.h=P,K.b=K.c=K.g=K.i="",K.e="t",K.j=true;for(var n,t=0;n=arguments[t];t++)for(var e in n)K[e]=n[e];t=K.a,K.d=/^[^,]+/.exec(t)[0],n=Function,t="return function("+t+"){",e=K;var r="var n,t="+e.d+",E="+e.e+";if(!t)return E;"+e.i+";";e.b?(r+="var u=t.length;n=-1;if("+e.b+"){",ct.unindexedChars&&(r+="if(s(t)){t=t.split('')}"),r+="while(++n<u){"+e.g+";}}else{"):ct.nonEnumArgs&&(r+="var u=t.length;n=-1;if(u&&p(t)){while(++n<u){n+='';"+e.g+";}}else{"),ct.enumPrototypes&&(r+="var G=typeof t=='function';"),ct.enumErrorProps&&(r+="var F=t===k||t instanceof Error;");
var o=[];if(ct.enumPrototypes&&o.push('!(G&&n=="prototype")'),ct.enumErrorProps&&o.push('!(F&&(n=="message"||n=="name"))'),e.j&&e.f)r+="var C=-1,D=B[typeof t]&&v(t),u=D?D.length:0;while(++C<u){n=D[C];",o.length&&(r+="if("+o.join("&&")+"){"),r+=e.g+";",o.length&&(r+="}"),r+="}";else if(r+="for(n in t){",e.j&&o.push("m.call(t, n)"),o.length&&(r+="if("+o.join("&&")+"){"),r+=e.g+";",o.length&&(r+="}"),r+="}",ct.nonEnumShadows){for(r+="if(t!==A){var i=t.constructor,r=t===(i&&i.prototype),f=t===J?I:t===k?j:L.call(t),x=y[f];",k=0;7>k;k++)r+="n='"+e.h[k]+"';if((!(r&&x[n])&&m.call(t,n))",e.j||(r+="||(!x[n]&&t[n]!==A[n])"),r+="){"+e.g+"}";
r+="}"}return(e.b||ct.nonEnumArgs)&&(r+="}"),r+=e.c+";return E",n("d,j,k,m,o,p,q,s,v,A,B,y,I,J,L",t+r+"}")(a,I,H,Y,O,y,lt,h,K.f,V,G,at,R,W,M)}function p(n){return typeof n=="function"&&Q.test(n)}function g(t){var e,r;return!t||M.call(t)!=L||(e=t.constructor,b(e)&&!(e instanceof e))||!ct.argsClass&&y(t)||!ct.nodeClass&&n(t)?false:ct.ownLast?(vt(t,function(n,t,e){return r=Y.call(e,t),false}),false!==r):(vt(t,function(n,t){r=t}),typeof r=="undefined"||Y.call(t,r))}function y(n){return n&&typeof n=="object"&&typeof n.length=="number"&&M.call(n)==_||false
}function b(n){return typeof n=="function"}function v(n){return!(!n||!G[typeof n])}function h(n){return typeof n=="string"||n&&typeof n=="object"&&M.call(n)==R||false}function d(n,t,e){if(t&&typeof e=="undefined"&&lt(n)){e=-1;for(var r=n.length;++e<r&&false!==t(n[e],e,n););}else yt(n,t,e);return n}function m(n,t){return 2<arguments.length?l(n,17,e(arguments,2),null,t):l(n,1,null,null,t)}function j(n){return n}function E(){}var w=[],O={},x=40,S=/\w*$/,A=/^\s*function[ \n\r\t]+\w/,C=/\bthis\b/,P="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),_="[object Arguments]",D="[object Boolean]",F="[object Date]",I="[object Error]",B="[object Number]",L="[object Object]",N="[object RegExp]",R="[object String]",$={"[object Function]":false};
$[_]=$["[object Array]"]=$[D]=$[F]=$[B]=$[L]=$[N]=$[R]=true;var z={configurable:false,enumerable:false,value:null,writable:false},K={a:"",b:null,c:"",d:"",e:"",v:null,g:"",h:null,support:null,i:"",j:false},G={"boolean":false,"function":true,object:true,number:false,string:false,undefined:false},J=G[typeof window]&&window||this,T=G[typeof global]&&global;!T||T.global!==T&&T.window!==T||(J=T);var q=[],H=Error.prototype,V=Object.prototype,W=String.prototype,M=V.toString,Q=RegExp("^"+(M+"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/toString| for [^\]]+/g,".*?")+"$"),U=Function.prototype.toString,X=p(X=Object.getPrototypeOf)&&X,Y=V.hasOwnProperty,Z=q.push,nt=V.propertyIsEnumerable,tt=q.unshift,et=function(){try{var n={},t=p(t=Object.defineProperty)&&t,e=t(n,n,n)&&t
}catch(r){}return e}(),rt=p(rt=Object.create)&&rt,ot=p(ot=Array.isArray)&&ot,ut=p(ut=Object.keys)&&ut,it={};it["[object Array]"]=Array,it[D]=Boolean,it[F]=Date,it["[object Function]"]=Function,it[L]=Object,it[B]=Number,it[N]=RegExp,it[R]=String;var at={};at["[object Array]"]=at[F]=at[B]={constructor:true,toLocaleString:true,toString:true,valueOf:true},at[D]=at[R]={constructor:true,toString:true,valueOf:true},at[I]=at["[object Function]"]=at[N]={constructor:true,toString:true},at[L]={constructor:true},function(){for(var n=P.length;n--;){var t,e=P[n];
for(t in at)Y.call(at,t)&&!Y.call(at[t],e)&&(at[t][e]=false)}}();var ct=r.support={};!function(){function n(){this.x=1}var t={0:1,length:1},e=[];n.prototype={valueOf:1,y:1};for(var r in new n)e.push(r);for(r in arguments);ct.argsClass=M.call(arguments)==_,ct.argsObject=arguments.constructor==Object&&!(arguments instanceof Array),ct.enumErrorProps=nt.call(H,"message")||nt.call(H,"name"),ct.enumPrototypes=nt.call(n,"prototype"),ct.funcDecomp=!p(J.k)&&C.test(function(){return this}),ct.funcNames=typeof Function.name=="string",ct.nonEnumArgs=0!=r,ct.nonEnumShadows=!/valueOf/.test(e),ct.ownLast="x"!=e[0],ct.spliceObjects=(q.splice.call(t,0,1),!t[0]),ct.unindexedChars="xx"!="x"[0]+Object("x")[0];
try{ct.nodeClass=!(M.call(document)==L&&!({toString:0}+""))}catch(o){ct.nodeClass=true}}(1),rt||(i=function(){function n(){}return function(t){if(v(t)){n.prototype=t;var e=new n;n.prototype=null}return e||J.Object()}}());var ft=et?function(n,t){z.value=t,et(n,"__bindData__",z)}:E;ct.argsClass||(y=function(n){return n&&typeof n=="object"&&typeof n.length=="number"&&Y.call(n,"callee")&&!nt.call(n,"callee")||false});var lt=ot||function(n){return n&&typeof n=="object"&&typeof n.length=="number"&&"[object Array]"==M.call(n)||false
},st=s({a:"z",e:"[]",i:"if(!(B[typeof z]))return E",g:"E.push(n)"}),T=ut?function(n){return v(n)?ct.enumPrototypes&&typeof n=="function"||ct.nonEnumArgs&&n.length&&y(n)?st(n):ut(n):[]}:st,ot={a:"g,e,K",i:"e=e&&typeof K=='undefined'?e:d(e,K,3)",b:"typeof u=='number'",v:T,g:"if(e(t[n],n,g)===false)return E"},pt={a:"z,H,l",i:"var a=arguments,b=0,c=typeof l=='number'?2:a.length;while(++b<c){t=a[b];if(t&&B[typeof t]){",v:T,g:"if(typeof E[n]=='undefined')E[n]=t[n]",c:"}}"},gt={i:"if(!B[typeof t])return E;"+ot.i,b:false},yt=s(ot),bt=s(pt,{i:pt.i.replace(";",";if(c>3&&typeof a[c-2]=='function'){var e=d(a[--c-1],a[c--],2)}else if(c>2&&typeof a[c-1]=='function'){e=a[--c]}"),g:"E[n]=e?e(E[n],t[n]):t[n]"}),vt=s(ot,gt,{j:false}),ht=s(ot,gt);
b(/x/)&&(b=function(n){return typeof n=="function"&&"[object Function]"==M.call(n)});var dt=X?function(n){if(!n||M.call(n)!=L||!ct.argsClass&&y(n))return false;var t=n.valueOf,e=p(t)&&(e=X(t))&&X(e);return e?n==e||X(n)==e:g(n)}:g;r.assign=bt,r.bind=m,r.forEach=d,r.forIn=vt,r.forOwn=ht,r.keys=T,r.merge=function(n){var r=arguments,o=2;if(!v(n))return n;if("number"!=typeof r[2]&&(o=r.length),3<o&&"function"==typeof r[o-2])var u=a(r[--o-1],r[o--],2);else 2<o&&"function"==typeof r[o-1]&&(u=r[--o]);for(var r=e(arguments,1,o),i=-1,c=w.pop()||[],l=w.pop()||[];++i<o;)f(n,r[i],u,c,l);
return t(c),t(l),n},r.each=d,r.extend=bt,r.clone=function(n,t,e,r){return typeof t!="boolean"&&null!=t&&(r=e,e=t,t=false),u(n,t,typeof e=="function"&&a(e,r,1))},r.identity=j,r.isArguments=y,r.isArray=lt,r.isFunction=b,r.isObject=v,r.isPlainObject=dt,r.isString=h,r.noop=E,r.VERSION="2.4.1",typeof define=="function"&&typeof define.amd=="object"&&define.amd&& define(function(){return r})}).call(this);